# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: NOKIA_USERNAME
    value: $(USERNAME)
    readonly: true
  - name: NOKIA_PASSWORD
    value: $(PASSWORD)
    readonly: true
  - name: PLATO_PROJECT_NAME
    value: devops
    readonly: true


trigger:
- master

pool:
  name: 'umut-linux'

extends:
  template: plato-template.yml
  parameters:      
      NOKIA_USERNAME: {{ variables.NOKIA_USERNAME }}
      NOKIA_PASSWORD: {{ variables.NOKIA_PASSWORD }}
      PLATO_PROJECT_NAME: {{ variables.PLATO_PROJECT_NAME }}


    
