# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'umut-linux'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo $(NOKIA_USERNAME)
    echo $(NOKIA_PASSWORD)
  displayName: 'Run a multi-line script'
