# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: PLATO_SERVER_URL    
    value: "http://plato.dynamic.nsn-net.net"
  - name: NOKIA_USERNAME
    value: $(USERNAME)
    readonly: true
  - name: NOKIA_PASSWORD
    value: $(PASSWORD)
    readonly: true

trigger:
- master

pool:
  name: 'umut-linux'

steps:

# Here the assumption is curl and jq is installed on agent machine
- script: |
    echo "Try to login to Plato" 
    echo "URL : ${PLATO_SERVER_URL}"
    echo "Username: ${NOKIA_USERNAME}" 
    curl --noproxy "*" -H "Content-type: application/json" -X POST -s ${PLATO_SERVER_URL}/api/token/ -d "{ \"username\": \"${NOKIA_USERNAME}\" , \"password\": \"${NOKIA_PASSWORD}\" }"  > /tmp/tokens.txt
    

  displayName: 'Login to Plato'
