#Plato Trial Pipeline

variables:
  - name: NOKIA_USERNAME
    value: $(USERNAME)
    readonly: true
  - name: NOKIA_PASSWORD
    value: $(PASSWORD)
    readonly: true
  - name: PLATO_PROJECT_NAME
    value: devops
    readonly: true


trigger:
- master

pool:
  name: 'umut-linux'

extends:
  template: plato-template.yml
  parameters:      
      test: true


    
