#Plato Trial Pipeline

variables:
  - name: NOKIA_USERNAME
    value: $(USERNAME)
    readonly: true
  - name: NOKIA_PASSWORD
    value: $(PASSWORD)
    readonly: true
  - name: PLATO_PROJECT_NAME
    value: devops
    readonly: true


#trigger:
#- master

pool:
  name: 'umut-linux'

extends:
  template: plato-template.yaml
  parameters:      
      NOKIA_USERNAME: $(NOKIA_USERNAME)
      NOKIA_PASSWORD: $(NOKIA_PASSWORD)
      PLATO_PROJECT_NAME: $(PLATO_PROJECT_NAME)
      PLATO_FILE_LOCATION: '/tmp/file.xlsx'
      PLATO_TOKEN_LOCATION: '/tmp/tokens.txt'


    
